// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/camera_lens.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcamera_5flens_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcamera_5flens_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fcamera_5flens_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fcamera_5flens_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fcamera_5flens_2eproto;
namespace ignition {
namespace msgs {
class CameraLens;
class CameraLensDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern CameraLensDefaultTypeInternal _CameraLens_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraLens* Arena::CreateMaybeMessage<::ignition::msgs::CameraLens>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE CameraLens PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.CameraLens) */ {
 public:
  inline CameraLens() : CameraLens(nullptr) {};
  virtual ~CameraLens();

  CameraLens(const CameraLens& from);
  CameraLens(CameraLens&& from) noexcept
    : CameraLens() {
    *this = ::std::move(from);
  }

  inline CameraLens& operator=(const CameraLens& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraLens& operator=(CameraLens&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CameraLens& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CameraLens* internal_default_instance() {
    return reinterpret_cast<const CameraLens*>(
               &_CameraLens_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CameraLens& a, CameraLens& b) {
    a.Swap(&b);
  }
  inline void Swap(CameraLens* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraLens* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CameraLens* New() const final {
    return CreateMaybeMessage<CameraLens>(nullptr);
  }

  CameraLens* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CameraLens>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CameraLens& from);
  void MergeFrom(const CameraLens& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CameraLens* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.CameraLens";
  }
  protected:
  explicit CameraLens(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fcamera_5flens_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fcamera_5flens_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 2,
    kFunFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kC1FieldNumber = 3,
    kC2FieldNumber = 4,
    kC3FieldNumber = 5,
    kFFieldNumber = 6,
    kCutoffAngleFieldNumber = 9,
    kScaleToHfovFieldNumber = 8,
    kEnvTextureSizeFieldNumber = 11,
    kHfovFieldNumber = 10,
  };
  // string type = 2;
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_type(
      std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string fun = 7;
  void clear_fun();
  const std::string& fun() const;
  void set_fun(const std::string& value);
  void set_fun(std::string&& value);
  void set_fun(const char* value);
  void set_fun(const char* value, size_t size);
  std::string* mutable_fun();
  std::string* release_fun();
  void set_allocated_fun(std::string* fun);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fun();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fun(
      std::string* fun);
  private:
  const std::string& _internal_fun() const;
  void _internal_set_fun(const std::string& value);
  std::string* _internal_mutable_fun();
  public:

  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // double c1 = 3;
  void clear_c1();
  double c1() const;
  void set_c1(double value);
  private:
  double _internal_c1() const;
  void _internal_set_c1(double value);
  public:

  // double c2 = 4;
  void clear_c2();
  double c2() const;
  void set_c2(double value);
  private:
  double _internal_c2() const;
  void _internal_set_c2(double value);
  public:

  // double c3 = 5;
  void clear_c3();
  double c3() const;
  void set_c3(double value);
  private:
  double _internal_c3() const;
  void _internal_set_c3(double value);
  public:

  // double f = 6;
  void clear_f();
  double f() const;
  void set_f(double value);
  private:
  double _internal_f() const;
  void _internal_set_f(double value);
  public:

  // double cutoff_angle = 9;
  void clear_cutoff_angle();
  double cutoff_angle() const;
  void set_cutoff_angle(double value);
  private:
  double _internal_cutoff_angle() const;
  void _internal_set_cutoff_angle(double value);
  public:

  // bool scale_to_hfov = 8;
  void clear_scale_to_hfov();
  bool scale_to_hfov() const;
  void set_scale_to_hfov(bool value);
  private:
  bool _internal_scale_to_hfov() const;
  void _internal_set_scale_to_hfov(bool value);
  public:

  // int32 env_texture_size = 11;
  void clear_env_texture_size();
  ::PROTOBUF_NAMESPACE_ID::int32 env_texture_size() const;
  void set_env_texture_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_env_texture_size() const;
  void _internal_set_env_texture_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // double hfov = 10;
  void clear_hfov();
  double hfov() const;
  void set_hfov(double value);
  private:
  double _internal_hfov() const;
  void _internal_set_hfov(double value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.CameraLens)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fun_;
  ::ignition::msgs::Header* header_;
  double c1_;
  double c2_;
  double c3_;
  double f_;
  double cutoff_angle_;
  bool scale_to_hfov_;
  ::PROTOBUF_NAMESPACE_ID::int32 env_texture_size_;
  double hfov_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fcamera_5flens_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CameraLens

// .ignition.msgs.Header header = 1;
inline bool CameraLens::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool CameraLens::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& CameraLens::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& CameraLens::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.header)
  return _internal_header();
}
inline void CameraLens::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.CameraLens.header)
}
inline ::ignition::msgs::Header* CameraLens::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* CameraLens::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.CameraLens.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* CameraLens::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* CameraLens::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.CameraLens.header)
  return _internal_mutable_header();
}
inline void CameraLens::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.CameraLens.header)
}

// string type = 2;
inline void CameraLens::clear_type() {
  type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CameraLens::type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.type)
  return _internal_type();
}
inline void CameraLens::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.type)
}
inline std::string* CameraLens::mutable_type() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.CameraLens.type)
  return _internal_mutable_type();
}
inline const std::string& CameraLens::_internal_type() const {
  return type_.Get();
}
inline void CameraLens::_internal_set_type(const std::string& value) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CameraLens::set_type(std::string&& value) {
  
  type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.CameraLens.type)
}
inline void CameraLens::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.CameraLens.type)
}
inline void CameraLens::set_type(const char* value,
    size_t size) {
  
  type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.CameraLens.type)
}
inline std::string* CameraLens::_internal_mutable_type() {
  
  return type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CameraLens::release_type() {
  // @@protoc_insertion_point(field_release:ignition.msgs.CameraLens.type)
  return type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CameraLens::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.CameraLens.type)
}
inline std::string* CameraLens::unsafe_arena_release_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.CameraLens.type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CameraLens::unsafe_arena_set_allocated_type(
    std::string* type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (type != nullptr) {
    
  } else {
    
  }
  type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.CameraLens.type)
}

// double c1 = 3;
inline void CameraLens::clear_c1() {
  c1_ = 0;
}
inline double CameraLens::_internal_c1() const {
  return c1_;
}
inline double CameraLens::c1() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.c1)
  return _internal_c1();
}
inline void CameraLens::_internal_set_c1(double value) {
  
  c1_ = value;
}
inline void CameraLens::set_c1(double value) {
  _internal_set_c1(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.c1)
}

// double c2 = 4;
inline void CameraLens::clear_c2() {
  c2_ = 0;
}
inline double CameraLens::_internal_c2() const {
  return c2_;
}
inline double CameraLens::c2() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.c2)
  return _internal_c2();
}
inline void CameraLens::_internal_set_c2(double value) {
  
  c2_ = value;
}
inline void CameraLens::set_c2(double value) {
  _internal_set_c2(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.c2)
}

// double c3 = 5;
inline void CameraLens::clear_c3() {
  c3_ = 0;
}
inline double CameraLens::_internal_c3() const {
  return c3_;
}
inline double CameraLens::c3() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.c3)
  return _internal_c3();
}
inline void CameraLens::_internal_set_c3(double value) {
  
  c3_ = value;
}
inline void CameraLens::set_c3(double value) {
  _internal_set_c3(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.c3)
}

// double f = 6;
inline void CameraLens::clear_f() {
  f_ = 0;
}
inline double CameraLens::_internal_f() const {
  return f_;
}
inline double CameraLens::f() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.f)
  return _internal_f();
}
inline void CameraLens::_internal_set_f(double value) {
  
  f_ = value;
}
inline void CameraLens::set_f(double value) {
  _internal_set_f(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.f)
}

// string fun = 7;
inline void CameraLens::clear_fun() {
  fun_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CameraLens::fun() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.fun)
  return _internal_fun();
}
inline void CameraLens::set_fun(const std::string& value) {
  _internal_set_fun(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.fun)
}
inline std::string* CameraLens::mutable_fun() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.CameraLens.fun)
  return _internal_mutable_fun();
}
inline const std::string& CameraLens::_internal_fun() const {
  return fun_.Get();
}
inline void CameraLens::_internal_set_fun(const std::string& value) {
  
  fun_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CameraLens::set_fun(std::string&& value) {
  
  fun_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.CameraLens.fun)
}
inline void CameraLens::set_fun(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fun_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.CameraLens.fun)
}
inline void CameraLens::set_fun(const char* value,
    size_t size) {
  
  fun_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.CameraLens.fun)
}
inline std::string* CameraLens::_internal_mutable_fun() {
  
  return fun_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CameraLens::release_fun() {
  // @@protoc_insertion_point(field_release:ignition.msgs.CameraLens.fun)
  return fun_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CameraLens::set_allocated_fun(std::string* fun) {
  if (fun != nullptr) {
    
  } else {
    
  }
  fun_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fun,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.CameraLens.fun)
}
inline std::string* CameraLens::unsafe_arena_release_fun() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.CameraLens.fun)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return fun_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CameraLens::unsafe_arena_set_allocated_fun(
    std::string* fun) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fun != nullptr) {
    
  } else {
    
  }
  fun_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fun, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.CameraLens.fun)
}

// bool scale_to_hfov = 8;
inline void CameraLens::clear_scale_to_hfov() {
  scale_to_hfov_ = false;
}
inline bool CameraLens::_internal_scale_to_hfov() const {
  return scale_to_hfov_;
}
inline bool CameraLens::scale_to_hfov() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.scale_to_hfov)
  return _internal_scale_to_hfov();
}
inline void CameraLens::_internal_set_scale_to_hfov(bool value) {
  
  scale_to_hfov_ = value;
}
inline void CameraLens::set_scale_to_hfov(bool value) {
  _internal_set_scale_to_hfov(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.scale_to_hfov)
}

// double cutoff_angle = 9;
inline void CameraLens::clear_cutoff_angle() {
  cutoff_angle_ = 0;
}
inline double CameraLens::_internal_cutoff_angle() const {
  return cutoff_angle_;
}
inline double CameraLens::cutoff_angle() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.cutoff_angle)
  return _internal_cutoff_angle();
}
inline void CameraLens::_internal_set_cutoff_angle(double value) {
  
  cutoff_angle_ = value;
}
inline void CameraLens::set_cutoff_angle(double value) {
  _internal_set_cutoff_angle(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.cutoff_angle)
}

// double hfov = 10;
inline void CameraLens::clear_hfov() {
  hfov_ = 0;
}
inline double CameraLens::_internal_hfov() const {
  return hfov_;
}
inline double CameraLens::hfov() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.hfov)
  return _internal_hfov();
}
inline void CameraLens::_internal_set_hfov(double value) {
  
  hfov_ = value;
}
inline void CameraLens::set_hfov(double value) {
  _internal_set_hfov(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.hfov)
}

// int32 env_texture_size = 11;
inline void CameraLens::clear_env_texture_size() {
  env_texture_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CameraLens::_internal_env_texture_size() const {
  return env_texture_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CameraLens::env_texture_size() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.CameraLens.env_texture_size)
  return _internal_env_texture_size();
}
inline void CameraLens::_internal_set_env_texture_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  env_texture_size_ = value;
}
inline void CameraLens::set_env_texture_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_env_texture_size(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.CameraLens.env_texture_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<CameraLens> CameraLensUniquePtr;
typedef std::unique_ptr<const CameraLens> ConstCameraLensUniquePtr;
typedef std::shared_ptr<CameraLens> CameraLensSharedPtr;
typedef std::shared_ptr<const CameraLens> ConstCameraLensSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fcamera_5flens_2eproto
