// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/fog.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/color.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2ffog_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2ffog_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2ffog_2eproto;
namespace ignition {
namespace msgs {
class Fog;
class FogDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern FogDefaultTypeInternal _Fog_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Fog* Arena::CreateMaybeMessage<::ignition::msgs::Fog>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

enum Fog_FogType : int {
  Fog_FogType_NONE = 0,
  Fog_FogType_LINEAR = 1,
  Fog_FogType_EXPONENTIAL = 2,
  Fog_FogType_EXPONENTIAL2 = 3,
  Fog_FogType_Fog_FogType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Fog_FogType_Fog_FogType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
IGNITION_MSGS_VISIBLE bool Fog_FogType_IsValid(int value);
constexpr Fog_FogType Fog_FogType_FogType_MIN = Fog_FogType_NONE;
constexpr Fog_FogType Fog_FogType_FogType_MAX = Fog_FogType_EXPONENTIAL2;
constexpr int Fog_FogType_FogType_ARRAYSIZE = Fog_FogType_FogType_MAX + 1;

IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Fog_FogType_descriptor();
template<typename T>
inline const std::string& Fog_FogType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Fog_FogType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Fog_FogType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Fog_FogType_descriptor(), enum_t_value);
}
inline bool Fog_FogType_Parse(
    const std::string& name, Fog_FogType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Fog_FogType>(
    Fog_FogType_descriptor(), name, value);
}
// ===================================================================

class IGNITION_MSGS_VISIBLE Fog PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Fog) */ {
 public:
  inline Fog() : Fog(nullptr) {};
  virtual ~Fog();

  Fog(const Fog& from);
  Fog(Fog&& from) noexcept
    : Fog() {
    *this = ::std::move(from);
  }

  inline Fog& operator=(const Fog& from) {
    CopyFrom(from);
    return *this;
  }
  inline Fog& operator=(Fog&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Fog& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Fog* internal_default_instance() {
    return reinterpret_cast<const Fog*>(
               &_Fog_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Fog& a, Fog& b) {
    a.Swap(&b);
  }
  inline void Swap(Fog* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Fog* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Fog* New() const final {
    return CreateMaybeMessage<Fog>(nullptr);
  }

  Fog* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Fog>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Fog& from);
  void MergeFrom(const Fog& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Fog* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Fog";
  }
  protected:
  explicit Fog(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2ffog_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2ffog_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Fog_FogType FogType;
  static constexpr FogType NONE =
    Fog_FogType_NONE;
  static constexpr FogType LINEAR =
    Fog_FogType_LINEAR;
  static constexpr FogType EXPONENTIAL =
    Fog_FogType_EXPONENTIAL;
  static constexpr FogType EXPONENTIAL2 =
    Fog_FogType_EXPONENTIAL2;
  static inline bool FogType_IsValid(int value) {
    return Fog_FogType_IsValid(value);
  }
  static constexpr FogType FogType_MIN =
    Fog_FogType_FogType_MIN;
  static constexpr FogType FogType_MAX =
    Fog_FogType_FogType_MAX;
  static constexpr int FogType_ARRAYSIZE =
    Fog_FogType_FogType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  FogType_descriptor() {
    return Fog_FogType_descriptor();
  }
  template<typename T>
  static inline const std::string& FogType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, FogType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function FogType_Name.");
    return Fog_FogType_Name(enum_t_value);
  }
  static inline bool FogType_Parse(const std::string& name,
      FogType* value) {
    return Fog_FogType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kColorFieldNumber = 3,
    kTypeFieldNumber = 2,
    kDensityFieldNumber = 4,
    kStartFieldNumber = 5,
    kEndFieldNumber = 6,
  };
  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // .ignition.msgs.Color color = 3;
  bool has_color() const;
  private:
  bool _internal_has_color() const;
  public:
  void clear_color();
  const ::ignition::msgs::Color& color() const;
  ::ignition::msgs::Color* release_color();
  ::ignition::msgs::Color* mutable_color();
  void set_allocated_color(::ignition::msgs::Color* color);
  private:
  const ::ignition::msgs::Color& _internal_color() const;
  ::ignition::msgs::Color* _internal_mutable_color();
  public:
  void unsafe_arena_set_allocated_color(
      ::ignition::msgs::Color* color);
  ::ignition::msgs::Color* unsafe_arena_release_color();

  // .ignition.msgs.Fog.FogType type = 2;
  void clear_type();
  ::ignition::msgs::Fog_FogType type() const;
  void set_type(::ignition::msgs::Fog_FogType value);
  private:
  ::ignition::msgs::Fog_FogType _internal_type() const;
  void _internal_set_type(::ignition::msgs::Fog_FogType value);
  public:

  // float density = 4;
  void clear_density();
  float density() const;
  void set_density(float value);
  private:
  float _internal_density() const;
  void _internal_set_density(float value);
  public:

  // float start = 5;
  void clear_start();
  float start() const;
  void set_start(float value);
  private:
  float _internal_start() const;
  void _internal_set_start(float value);
  public:

  // float end = 6;
  void clear_end();
  float end() const;
  void set_end(float value);
  private:
  float _internal_end() const;
  void _internal_set_end(float value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.Fog)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Color* color_;
  int type_;
  float density_;
  float start_;
  float end_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2ffog_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Fog

// .ignition.msgs.Header header = 1;
inline bool Fog::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Fog::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& Fog::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& Fog::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.header)
  return _internal_header();
}
inline void Fog::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Fog.header)
}
inline ::ignition::msgs::Header* Fog::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* Fog::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Fog.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Fog::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* Fog::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Fog.header)
  return _internal_mutable_header();
}
inline void Fog::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Fog.header)
}

// .ignition.msgs.Fog.FogType type = 2;
inline void Fog::clear_type() {
  type_ = 0;
}
inline ::ignition::msgs::Fog_FogType Fog::_internal_type() const {
  return static_cast< ::ignition::msgs::Fog_FogType >(type_);
}
inline ::ignition::msgs::Fog_FogType Fog::type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.type)
  return _internal_type();
}
inline void Fog::_internal_set_type(::ignition::msgs::Fog_FogType value) {
  
  type_ = value;
}
inline void Fog::set_type(::ignition::msgs::Fog_FogType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.type)
}

// .ignition.msgs.Color color = 3;
inline bool Fog::_internal_has_color() const {
  return this != internal_default_instance() && color_ != nullptr;
}
inline bool Fog::has_color() const {
  return _internal_has_color();
}
inline const ::ignition::msgs::Color& Fog::_internal_color() const {
  const ::ignition::msgs::Color* p = color_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Color*>(
      &::ignition::msgs::_Color_default_instance_);
}
inline const ::ignition::msgs::Color& Fog::color() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.color)
  return _internal_color();
}
inline void Fog::unsafe_arena_set_allocated_color(
    ::ignition::msgs::Color* color) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(color_);
  }
  color_ = color;
  if (color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Fog.color)
}
inline ::ignition::msgs::Color* Fog::release_color() {
  auto temp = unsafe_arena_release_color();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Color* Fog::unsafe_arena_release_color() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Fog.color)
  
  ::ignition::msgs::Color* temp = color_;
  color_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Color* Fog::_internal_mutable_color() {
  
  if (color_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Color>(GetArena());
    color_ = p;
  }
  return color_;
}
inline ::ignition::msgs::Color* Fog::mutable_color() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Fog.color)
  return _internal_mutable_color();
}
inline void Fog::set_allocated_color(::ignition::msgs::Color* color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(color_);
  }
  if (color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(color)->GetArena();
    if (message_arena != submessage_arena) {
      color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    
  } else {
    
  }
  color_ = color;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Fog.color)
}

// float density = 4;
inline void Fog::clear_density() {
  density_ = 0;
}
inline float Fog::_internal_density() const {
  return density_;
}
inline float Fog::density() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.density)
  return _internal_density();
}
inline void Fog::_internal_set_density(float value) {
  
  density_ = value;
}
inline void Fog::set_density(float value) {
  _internal_set_density(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.density)
}

// float start = 5;
inline void Fog::clear_start() {
  start_ = 0;
}
inline float Fog::_internal_start() const {
  return start_;
}
inline float Fog::start() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.start)
  return _internal_start();
}
inline void Fog::_internal_set_start(float value) {
  
  start_ = value;
}
inline void Fog::set_start(float value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.start)
}

// float end = 6;
inline void Fog::clear_end() {
  end_ = 0;
}
inline float Fog::_internal_end() const {
  return end_;
}
inline float Fog::end() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Fog.end)
  return _internal_end();
}
inline void Fog::_internal_set_end(float value) {
  
  end_ = value;
}
inline void Fog::set_end(float value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Fog.end)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<Fog> FogUniquePtr;
typedef std::unique_ptr<const Fog> ConstFogUniquePtr;
typedef std::shared_ptr<Fog> FogSharedPtr;
typedef std::shared_ptr<const Fog> ConstFogSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ignition::msgs::Fog_FogType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ignition::msgs::Fog_FogType>() {
  return ::ignition::msgs::Fog_FogType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2ffog_2eproto
