// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/joint.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#include "ignition/msgs/axis.pb.h"
#include "ignition/msgs/pose.pb.h"
#include "ignition/msgs/sensor.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fjoint_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fjoint_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fjoint_2eproto;
namespace ignition {
namespace msgs {
class Joint;
class JointDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern JointDefaultTypeInternal _Joint_default_instance_;
class Joint_Gearbox;
class Joint_GearboxDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern Joint_GearboxDefaultTypeInternal _Joint_Gearbox_default_instance_;
class Joint_Screw;
class Joint_ScrewDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern Joint_ScrewDefaultTypeInternal _Joint_Screw_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint* Arena::CreateMaybeMessage<::ignition::msgs::Joint>(Arena*);
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Gearbox* Arena::CreateMaybeMessage<::ignition::msgs::Joint_Gearbox>(Arena*);
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Screw* Arena::CreateMaybeMessage<::ignition::msgs::Joint_Screw>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

enum Joint_Type : int {
  Joint_Type_REVOLUTE = 0,
  Joint_Type_REVOLUTE2 = 1,
  Joint_Type_PRISMATIC = 2,
  Joint_Type_UNIVERSAL = 3,
  Joint_Type_BALL = 4,
  Joint_Type_SCREW = 5,
  Joint_Type_GEARBOX = 6,
  Joint_Type_FIXED = 7,
  Joint_Type_Joint_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Joint_Type_Joint_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
IGNITION_MSGS_VISIBLE bool Joint_Type_IsValid(int value);
constexpr Joint_Type Joint_Type_Type_MIN = Joint_Type_REVOLUTE;
constexpr Joint_Type Joint_Type_Type_MAX = Joint_Type_FIXED;
constexpr int Joint_Type_Type_ARRAYSIZE = Joint_Type_Type_MAX + 1;

IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Joint_Type_descriptor();
template<typename T>
inline const std::string& Joint_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Joint_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Joint_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Joint_Type_descriptor(), enum_t_value);
}
inline bool Joint_Type_Parse(
    const std::string& name, Joint_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Joint_Type>(
    Joint_Type_descriptor(), name, value);
}
// ===================================================================

class IGNITION_MSGS_VISIBLE Joint_Gearbox PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Joint.Gearbox) */ {
 public:
  inline Joint_Gearbox() : Joint_Gearbox(nullptr) {};
  virtual ~Joint_Gearbox();

  Joint_Gearbox(const Joint_Gearbox& from);
  Joint_Gearbox(Joint_Gearbox&& from) noexcept
    : Joint_Gearbox() {
    *this = ::std::move(from);
  }

  inline Joint_Gearbox& operator=(const Joint_Gearbox& from) {
    CopyFrom(from);
    return *this;
  }
  inline Joint_Gearbox& operator=(Joint_Gearbox&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Joint_Gearbox& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Joint_Gearbox* internal_default_instance() {
    return reinterpret_cast<const Joint_Gearbox*>(
               &_Joint_Gearbox_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Joint_Gearbox& a, Joint_Gearbox& b) {
    a.Swap(&b);
  }
  inline void Swap(Joint_Gearbox* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Joint_Gearbox* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Joint_Gearbox* New() const final {
    return CreateMaybeMessage<Joint_Gearbox>(nullptr);
  }

  Joint_Gearbox* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Joint_Gearbox>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Joint_Gearbox& from);
  void MergeFrom(const Joint_Gearbox& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Joint_Gearbox* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Joint.Gearbox";
  }
  protected:
  explicit Joint_Gearbox(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fjoint_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fjoint_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGearboxReferenceBodyFieldNumber = 1,
    kGearboxRatioFieldNumber = 2,
  };
  // string gearbox_reference_body = 1;
  void clear_gearbox_reference_body();
  const std::string& gearbox_reference_body() const;
  void set_gearbox_reference_body(const std::string& value);
  void set_gearbox_reference_body(std::string&& value);
  void set_gearbox_reference_body(const char* value);
  void set_gearbox_reference_body(const char* value, size_t size);
  std::string* mutable_gearbox_reference_body();
  std::string* release_gearbox_reference_body();
  void set_allocated_gearbox_reference_body(std::string* gearbox_reference_body);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_gearbox_reference_body();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_gearbox_reference_body(
      std::string* gearbox_reference_body);
  private:
  const std::string& _internal_gearbox_reference_body() const;
  void _internal_set_gearbox_reference_body(const std::string& value);
  std::string* _internal_mutable_gearbox_reference_body();
  public:

  // double gearbox_ratio = 2;
  void clear_gearbox_ratio();
  double gearbox_ratio() const;
  void set_gearbox_ratio(double value);
  private:
  double _internal_gearbox_ratio() const;
  void _internal_set_gearbox_ratio(double value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.Joint.Gearbox)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gearbox_reference_body_;
  double gearbox_ratio_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fjoint_2eproto;
};
// -------------------------------------------------------------------

class IGNITION_MSGS_VISIBLE Joint_Screw PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Joint.Screw) */ {
 public:
  inline Joint_Screw() : Joint_Screw(nullptr) {};
  virtual ~Joint_Screw();

  Joint_Screw(const Joint_Screw& from);
  Joint_Screw(Joint_Screw&& from) noexcept
    : Joint_Screw() {
    *this = ::std::move(from);
  }

  inline Joint_Screw& operator=(const Joint_Screw& from) {
    CopyFrom(from);
    return *this;
  }
  inline Joint_Screw& operator=(Joint_Screw&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Joint_Screw& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Joint_Screw* internal_default_instance() {
    return reinterpret_cast<const Joint_Screw*>(
               &_Joint_Screw_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Joint_Screw& a, Joint_Screw& b) {
    a.Swap(&b);
  }
  inline void Swap(Joint_Screw* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Joint_Screw* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Joint_Screw* New() const final {
    return CreateMaybeMessage<Joint_Screw>(nullptr);
  }

  Joint_Screw* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Joint_Screw>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Joint_Screw& from);
  void MergeFrom(const Joint_Screw& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Joint_Screw* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Joint.Screw";
  }
  protected:
  explicit Joint_Screw(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fjoint_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fjoint_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kThreadPitchFieldNumber = 1,
  };
  // double thread_pitch = 1;
  void clear_thread_pitch();
  double thread_pitch() const;
  void set_thread_pitch(double value);
  private:
  double _internal_thread_pitch() const;
  void _internal_set_thread_pitch(double value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.Joint.Screw)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double thread_pitch_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fjoint_2eproto;
};
// -------------------------------------------------------------------

class IGNITION_MSGS_VISIBLE Joint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Joint) */ {
 public:
  inline Joint() : Joint(nullptr) {};
  virtual ~Joint();

  Joint(const Joint& from);
  Joint(Joint&& from) noexcept
    : Joint() {
    *this = ::std::move(from);
  }

  inline Joint& operator=(const Joint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Joint& operator=(Joint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Joint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Joint* internal_default_instance() {
    return reinterpret_cast<const Joint*>(
               &_Joint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Joint& a, Joint& b) {
    a.Swap(&b);
  }
  inline void Swap(Joint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Joint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Joint* New() const final {
    return CreateMaybeMessage<Joint>(nullptr);
  }

  Joint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Joint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Joint& from);
  void MergeFrom(const Joint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Joint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Joint";
  }
  protected:
  explicit Joint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fjoint_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fjoint_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Joint_Gearbox Gearbox;
  typedef Joint_Screw Screw;

  typedef Joint_Type Type;
  static constexpr Type REVOLUTE =
    Joint_Type_REVOLUTE;
  static constexpr Type REVOLUTE2 =
    Joint_Type_REVOLUTE2;
  static constexpr Type PRISMATIC =
    Joint_Type_PRISMATIC;
  static constexpr Type UNIVERSAL =
    Joint_Type_UNIVERSAL;
  static constexpr Type BALL =
    Joint_Type_BALL;
  static constexpr Type SCREW =
    Joint_Type_SCREW;
  static constexpr Type GEARBOX =
    Joint_Type_GEARBOX;
  static constexpr Type FIXED =
    Joint_Type_FIXED;
  static inline bool Type_IsValid(int value) {
    return Joint_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Joint_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Joint_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Joint_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Joint_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Joint_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(const std::string& name,
      Type* value) {
    return Joint_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSensorFieldNumber = 21,
    kNameFieldNumber = 2,
    kParentFieldNumber = 5,
    kChildFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kPoseFieldNumber = 9,
    kAxis1FieldNumber = 10,
    kAxis2FieldNumber = 11,
    kGearboxFieldNumber = 19,
    kScrewFieldNumber = 20,
    kIdFieldNumber = 3,
    kTypeFieldNumber = 4,
    kParentIdFieldNumber = 6,
    kChildIdFieldNumber = 8,
    kCfmFieldNumber = 12,
    kBounceFieldNumber = 13,
    kFudgeFactorFieldNumber = 14,
    kLimitCfmFieldNumber = 15,
    kLimitErpFieldNumber = 16,
    kSuspensionCfmFieldNumber = 17,
    kSuspensionErpFieldNumber = 18,
  };
  // repeated .ignition.msgs.Sensor sensor = 21;
  int sensor_size() const;
  private:
  int _internal_sensor_size() const;
  public:
  void clear_sensor();
  ::ignition::msgs::Sensor* mutable_sensor(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Sensor >*
      mutable_sensor();
  private:
  const ::ignition::msgs::Sensor& _internal_sensor(int index) const;
  ::ignition::msgs::Sensor* _internal_add_sensor();
  public:
  const ::ignition::msgs::Sensor& sensor(int index) const;
  ::ignition::msgs::Sensor* add_sensor();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Sensor >&
      sensor() const;

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string parent = 5;
  void clear_parent();
  const std::string& parent() const;
  void set_parent(const std::string& value);
  void set_parent(std::string&& value);
  void set_parent(const char* value);
  void set_parent(const char* value, size_t size);
  std::string* mutable_parent();
  std::string* release_parent();
  void set_allocated_parent(std::string* parent);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_parent();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_parent(
      std::string* parent);
  private:
  const std::string& _internal_parent() const;
  void _internal_set_parent(const std::string& value);
  std::string* _internal_mutable_parent();
  public:

  // string child = 7;
  void clear_child();
  const std::string& child() const;
  void set_child(const std::string& value);
  void set_child(std::string&& value);
  void set_child(const char* value);
  void set_child(const char* value, size_t size);
  std::string* mutable_child();
  std::string* release_child();
  void set_allocated_child(std::string* child);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_child();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_child(
      std::string* child);
  private:
  const std::string& _internal_child() const;
  void _internal_set_child(const std::string& value);
  std::string* _internal_mutable_child();
  public:

  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // .ignition.msgs.Pose pose = 9;
  bool has_pose() const;
  private:
  bool _internal_has_pose() const;
  public:
  void clear_pose();
  const ::ignition::msgs::Pose& pose() const;
  ::ignition::msgs::Pose* release_pose();
  ::ignition::msgs::Pose* mutable_pose();
  void set_allocated_pose(::ignition::msgs::Pose* pose);
  private:
  const ::ignition::msgs::Pose& _internal_pose() const;
  ::ignition::msgs::Pose* _internal_mutable_pose();
  public:
  void unsafe_arena_set_allocated_pose(
      ::ignition::msgs::Pose* pose);
  ::ignition::msgs::Pose* unsafe_arena_release_pose();

  // .ignition.msgs.Axis axis1 = 10;
  bool has_axis1() const;
  private:
  bool _internal_has_axis1() const;
  public:
  void clear_axis1();
  const ::ignition::msgs::Axis& axis1() const;
  ::ignition::msgs::Axis* release_axis1();
  ::ignition::msgs::Axis* mutable_axis1();
  void set_allocated_axis1(::ignition::msgs::Axis* axis1);
  private:
  const ::ignition::msgs::Axis& _internal_axis1() const;
  ::ignition::msgs::Axis* _internal_mutable_axis1();
  public:
  void unsafe_arena_set_allocated_axis1(
      ::ignition::msgs::Axis* axis1);
  ::ignition::msgs::Axis* unsafe_arena_release_axis1();

  // .ignition.msgs.Axis axis2 = 11;
  bool has_axis2() const;
  private:
  bool _internal_has_axis2() const;
  public:
  void clear_axis2();
  const ::ignition::msgs::Axis& axis2() const;
  ::ignition::msgs::Axis* release_axis2();
  ::ignition::msgs::Axis* mutable_axis2();
  void set_allocated_axis2(::ignition::msgs::Axis* axis2);
  private:
  const ::ignition::msgs::Axis& _internal_axis2() const;
  ::ignition::msgs::Axis* _internal_mutable_axis2();
  public:
  void unsafe_arena_set_allocated_axis2(
      ::ignition::msgs::Axis* axis2);
  ::ignition::msgs::Axis* unsafe_arena_release_axis2();

  // .ignition.msgs.Joint.Gearbox gearbox = 19;
  bool has_gearbox() const;
  private:
  bool _internal_has_gearbox() const;
  public:
  void clear_gearbox();
  const ::ignition::msgs::Joint_Gearbox& gearbox() const;
  ::ignition::msgs::Joint_Gearbox* release_gearbox();
  ::ignition::msgs::Joint_Gearbox* mutable_gearbox();
  void set_allocated_gearbox(::ignition::msgs::Joint_Gearbox* gearbox);
  private:
  const ::ignition::msgs::Joint_Gearbox& _internal_gearbox() const;
  ::ignition::msgs::Joint_Gearbox* _internal_mutable_gearbox();
  public:
  void unsafe_arena_set_allocated_gearbox(
      ::ignition::msgs::Joint_Gearbox* gearbox);
  ::ignition::msgs::Joint_Gearbox* unsafe_arena_release_gearbox();

  // .ignition.msgs.Joint.Screw screw = 20;
  bool has_screw() const;
  private:
  bool _internal_has_screw() const;
  public:
  void clear_screw();
  const ::ignition::msgs::Joint_Screw& screw() const;
  ::ignition::msgs::Joint_Screw* release_screw();
  ::ignition::msgs::Joint_Screw* mutable_screw();
  void set_allocated_screw(::ignition::msgs::Joint_Screw* screw);
  private:
  const ::ignition::msgs::Joint_Screw& _internal_screw() const;
  ::ignition::msgs::Joint_Screw* _internal_mutable_screw();
  public:
  void unsafe_arena_set_allocated_screw(
      ::ignition::msgs::Joint_Screw* screw);
  ::ignition::msgs::Joint_Screw* unsafe_arena_release_screw();

  // uint32 id = 3;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // .ignition.msgs.Joint.Type type = 4;
  void clear_type();
  ::ignition::msgs::Joint_Type type() const;
  void set_type(::ignition::msgs::Joint_Type value);
  private:
  ::ignition::msgs::Joint_Type _internal_type() const;
  void _internal_set_type(::ignition::msgs::Joint_Type value);
  public:

  // uint32 parent_id = 6;
  void clear_parent_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 parent_id() const;
  void set_parent_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_parent_id() const;
  void _internal_set_parent_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 child_id = 8;
  void clear_child_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 child_id() const;
  void set_child_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_child_id() const;
  void _internal_set_child_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // double cfm = 12;
  void clear_cfm();
  double cfm() const;
  void set_cfm(double value);
  private:
  double _internal_cfm() const;
  void _internal_set_cfm(double value);
  public:

  // double bounce = 13;
  void clear_bounce();
  double bounce() const;
  void set_bounce(double value);
  private:
  double _internal_bounce() const;
  void _internal_set_bounce(double value);
  public:

  // double fudge_factor = 14;
  void clear_fudge_factor();
  double fudge_factor() const;
  void set_fudge_factor(double value);
  private:
  double _internal_fudge_factor() const;
  void _internal_set_fudge_factor(double value);
  public:

  // double limit_cfm = 15;
  void clear_limit_cfm();
  double limit_cfm() const;
  void set_limit_cfm(double value);
  private:
  double _internal_limit_cfm() const;
  void _internal_set_limit_cfm(double value);
  public:

  // double limit_erp = 16;
  void clear_limit_erp();
  double limit_erp() const;
  void set_limit_erp(double value);
  private:
  double _internal_limit_erp() const;
  void _internal_set_limit_erp(double value);
  public:

  // double suspension_cfm = 17;
  void clear_suspension_cfm();
  double suspension_cfm() const;
  void set_suspension_cfm(double value);
  private:
  double _internal_suspension_cfm() const;
  void _internal_set_suspension_cfm(double value);
  public:

  // double suspension_erp = 18;
  void clear_suspension_erp();
  double suspension_erp() const;
  void set_suspension_erp(double value);
  private:
  double _internal_suspension_erp() const;
  void _internal_set_suspension_erp(double value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.Joint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Sensor > sensor_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr child_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Pose* pose_;
  ::ignition::msgs::Axis* axis1_;
  ::ignition::msgs::Axis* axis2_;
  ::ignition::msgs::Joint_Gearbox* gearbox_;
  ::ignition::msgs::Joint_Screw* screw_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  int type_;
  ::PROTOBUF_NAMESPACE_ID::uint32 parent_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 child_id_;
  double cfm_;
  double bounce_;
  double fudge_factor_;
  double limit_cfm_;
  double limit_erp_;
  double suspension_cfm_;
  double suspension_erp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fjoint_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Joint_Gearbox

// string gearbox_reference_body = 1;
inline void Joint_Gearbox::clear_gearbox_reference_body() {
  gearbox_reference_body_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Joint_Gearbox::gearbox_reference_body() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
  return _internal_gearbox_reference_body();
}
inline void Joint_Gearbox::set_gearbox_reference_body(const std::string& value) {
  _internal_set_gearbox_reference_body(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}
inline std::string* Joint_Gearbox::mutable_gearbox_reference_body() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
  return _internal_mutable_gearbox_reference_body();
}
inline const std::string& Joint_Gearbox::_internal_gearbox_reference_body() const {
  return gearbox_reference_body_.Get();
}
inline void Joint_Gearbox::_internal_set_gearbox_reference_body(const std::string& value) {
  
  gearbox_reference_body_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Joint_Gearbox::set_gearbox_reference_body(std::string&& value) {
  
  gearbox_reference_body_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}
inline void Joint_Gearbox::set_gearbox_reference_body(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gearbox_reference_body_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}
inline void Joint_Gearbox::set_gearbox_reference_body(const char* value,
    size_t size) {
  
  gearbox_reference_body_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}
inline std::string* Joint_Gearbox::_internal_mutable_gearbox_reference_body() {
  
  return gearbox_reference_body_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Joint_Gearbox::release_gearbox_reference_body() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
  return gearbox_reference_body_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Joint_Gearbox::set_allocated_gearbox_reference_body(std::string* gearbox_reference_body) {
  if (gearbox_reference_body != nullptr) {
    
  } else {
    
  }
  gearbox_reference_body_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gearbox_reference_body,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}
inline std::string* Joint_Gearbox::unsafe_arena_release_gearbox_reference_body() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return gearbox_reference_body_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Joint_Gearbox::unsafe_arena_set_allocated_gearbox_reference_body(
    std::string* gearbox_reference_body) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (gearbox_reference_body != nullptr) {
    
  } else {
    
  }
  gearbox_reference_body_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      gearbox_reference_body, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.Gearbox.gearbox_reference_body)
}

// double gearbox_ratio = 2;
inline void Joint_Gearbox::clear_gearbox_ratio() {
  gearbox_ratio_ = 0;
}
inline double Joint_Gearbox::_internal_gearbox_ratio() const {
  return gearbox_ratio_;
}
inline double Joint_Gearbox::gearbox_ratio() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.Gearbox.gearbox_ratio)
  return _internal_gearbox_ratio();
}
inline void Joint_Gearbox::_internal_set_gearbox_ratio(double value) {
  
  gearbox_ratio_ = value;
}
inline void Joint_Gearbox::set_gearbox_ratio(double value) {
  _internal_set_gearbox_ratio(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.Gearbox.gearbox_ratio)
}

// -------------------------------------------------------------------

// Joint_Screw

// double thread_pitch = 1;
inline void Joint_Screw::clear_thread_pitch() {
  thread_pitch_ = 0;
}
inline double Joint_Screw::_internal_thread_pitch() const {
  return thread_pitch_;
}
inline double Joint_Screw::thread_pitch() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.Screw.thread_pitch)
  return _internal_thread_pitch();
}
inline void Joint_Screw::_internal_set_thread_pitch(double value) {
  
  thread_pitch_ = value;
}
inline void Joint_Screw::set_thread_pitch(double value) {
  _internal_set_thread_pitch(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.Screw.thread_pitch)
}

// -------------------------------------------------------------------

// Joint

// .ignition.msgs.Header header = 1;
inline bool Joint::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Joint::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& Joint::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& Joint::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.header)
  return _internal_header();
}
inline void Joint::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.header)
}
inline ::ignition::msgs::Header* Joint::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* Joint::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Joint::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* Joint::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.header)
  return _internal_mutable_header();
}
inline void Joint::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.header)
}

// string name = 2;
inline void Joint::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Joint::name() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.name)
  return _internal_name();
}
inline void Joint::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.name)
}
inline std::string* Joint::mutable_name() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.name)
  return _internal_mutable_name();
}
inline const std::string& Joint::_internal_name() const {
  return name_.Get();
}
inline void Joint::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Joint::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Joint.name)
}
inline void Joint::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Joint.name)
}
inline void Joint::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Joint.name)
}
inline std::string* Joint::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Joint::release_name() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Joint::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.name)
}
inline std::string* Joint::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.Joint.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Joint::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.name)
}

// uint32 id = 3;
inline void Joint::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::id() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.id)
  return _internal_id();
}
inline void Joint::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void Joint::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.id)
}

// .ignition.msgs.Joint.Type type = 4;
inline void Joint::clear_type() {
  type_ = 0;
}
inline ::ignition::msgs::Joint_Type Joint::_internal_type() const {
  return static_cast< ::ignition::msgs::Joint_Type >(type_);
}
inline ::ignition::msgs::Joint_Type Joint::type() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.type)
  return _internal_type();
}
inline void Joint::_internal_set_type(::ignition::msgs::Joint_Type value) {
  
  type_ = value;
}
inline void Joint::set_type(::ignition::msgs::Joint_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.type)
}

// string parent = 5;
inline void Joint::clear_parent() {
  parent_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Joint::parent() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.parent)
  return _internal_parent();
}
inline void Joint::set_parent(const std::string& value) {
  _internal_set_parent(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.parent)
}
inline std::string* Joint::mutable_parent() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.parent)
  return _internal_mutable_parent();
}
inline const std::string& Joint::_internal_parent() const {
  return parent_.Get();
}
inline void Joint::_internal_set_parent(const std::string& value) {
  
  parent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Joint::set_parent(std::string&& value) {
  
  parent_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Joint.parent)
}
inline void Joint::set_parent(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  parent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Joint.parent)
}
inline void Joint::set_parent(const char* value,
    size_t size) {
  
  parent_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Joint.parent)
}
inline std::string* Joint::_internal_mutable_parent() {
  
  return parent_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Joint::release_parent() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.parent)
  return parent_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Joint::set_allocated_parent(std::string* parent) {
  if (parent != nullptr) {
    
  } else {
    
  }
  parent_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), parent,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.parent)
}
inline std::string* Joint::unsafe_arena_release_parent() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.Joint.parent)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return parent_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Joint::unsafe_arena_set_allocated_parent(
    std::string* parent) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (parent != nullptr) {
    
  } else {
    
  }
  parent_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      parent, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.parent)
}

// uint32 parent_id = 6;
inline void Joint::clear_parent_id() {
  parent_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::_internal_parent_id() const {
  return parent_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::parent_id() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.parent_id)
  return _internal_parent_id();
}
inline void Joint::_internal_set_parent_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  parent_id_ = value;
}
inline void Joint::set_parent_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_parent_id(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.parent_id)
}

// string child = 7;
inline void Joint::clear_child() {
  child_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Joint::child() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.child)
  return _internal_child();
}
inline void Joint::set_child(const std::string& value) {
  _internal_set_child(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.child)
}
inline std::string* Joint::mutable_child() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.child)
  return _internal_mutable_child();
}
inline const std::string& Joint::_internal_child() const {
  return child_.Get();
}
inline void Joint::_internal_set_child(const std::string& value) {
  
  child_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Joint::set_child(std::string&& value) {
  
  child_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ignition.msgs.Joint.child)
}
inline void Joint::set_child(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  child_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:ignition.msgs.Joint.child)
}
inline void Joint::set_child(const char* value,
    size_t size) {
  
  child_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ignition.msgs.Joint.child)
}
inline std::string* Joint::_internal_mutable_child() {
  
  return child_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Joint::release_child() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.child)
  return child_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Joint::set_allocated_child(std::string* child) {
  if (child != nullptr) {
    
  } else {
    
  }
  child_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), child,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.child)
}
inline std::string* Joint::unsafe_arena_release_child() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ignition.msgs.Joint.child)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return child_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Joint::unsafe_arena_set_allocated_child(
    std::string* child) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (child != nullptr) {
    
  } else {
    
  }
  child_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      child, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.child)
}

// uint32 child_id = 8;
inline void Joint::clear_child_id() {
  child_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::_internal_child_id() const {
  return child_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Joint::child_id() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.child_id)
  return _internal_child_id();
}
inline void Joint::_internal_set_child_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  child_id_ = value;
}
inline void Joint::set_child_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_child_id(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.child_id)
}

// .ignition.msgs.Pose pose = 9;
inline bool Joint::_internal_has_pose() const {
  return this != internal_default_instance() && pose_ != nullptr;
}
inline bool Joint::has_pose() const {
  return _internal_has_pose();
}
inline const ::ignition::msgs::Pose& Joint::_internal_pose() const {
  const ::ignition::msgs::Pose* p = pose_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Pose*>(
      &::ignition::msgs::_Pose_default_instance_);
}
inline const ::ignition::msgs::Pose& Joint::pose() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.pose)
  return _internal_pose();
}
inline void Joint::unsafe_arena_set_allocated_pose(
    ::ignition::msgs::Pose* pose) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  pose_ = pose;
  if (pose) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.pose)
}
inline ::ignition::msgs::Pose* Joint::release_pose() {
  auto temp = unsafe_arena_release_pose();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Pose* Joint::unsafe_arena_release_pose() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.pose)
  
  ::ignition::msgs::Pose* temp = pose_;
  pose_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Pose* Joint::_internal_mutable_pose() {
  
  if (pose_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Pose>(GetArena());
    pose_ = p;
  }
  return pose_;
}
inline ::ignition::msgs::Pose* Joint::mutable_pose() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.pose)
  return _internal_mutable_pose();
}
inline void Joint::set_allocated_pose(::ignition::msgs::Pose* pose) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose_);
  }
  if (pose) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pose)->GetArena();
    if (message_arena != submessage_arena) {
      pose = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.pose)
}

// .ignition.msgs.Axis axis1 = 10;
inline bool Joint::_internal_has_axis1() const {
  return this != internal_default_instance() && axis1_ != nullptr;
}
inline bool Joint::has_axis1() const {
  return _internal_has_axis1();
}
inline const ::ignition::msgs::Axis& Joint::_internal_axis1() const {
  const ::ignition::msgs::Axis* p = axis1_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Axis*>(
      &::ignition::msgs::_Axis_default_instance_);
}
inline const ::ignition::msgs::Axis& Joint::axis1() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.axis1)
  return _internal_axis1();
}
inline void Joint::unsafe_arena_set_allocated_axis1(
    ::ignition::msgs::Axis* axis1) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis1_);
  }
  axis1_ = axis1;
  if (axis1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.axis1)
}
inline ::ignition::msgs::Axis* Joint::release_axis1() {
  auto temp = unsafe_arena_release_axis1();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Axis* Joint::unsafe_arena_release_axis1() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.axis1)
  
  ::ignition::msgs::Axis* temp = axis1_;
  axis1_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Axis* Joint::_internal_mutable_axis1() {
  
  if (axis1_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Axis>(GetArena());
    axis1_ = p;
  }
  return axis1_;
}
inline ::ignition::msgs::Axis* Joint::mutable_axis1() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.axis1)
  return _internal_mutable_axis1();
}
inline void Joint::set_allocated_axis1(::ignition::msgs::Axis* axis1) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis1_);
  }
  if (axis1) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis1)->GetArena();
    if (message_arena != submessage_arena) {
      axis1 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, axis1, submessage_arena);
    }
    
  } else {
    
  }
  axis1_ = axis1;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.axis1)
}

// .ignition.msgs.Axis axis2 = 11;
inline bool Joint::_internal_has_axis2() const {
  return this != internal_default_instance() && axis2_ != nullptr;
}
inline bool Joint::has_axis2() const {
  return _internal_has_axis2();
}
inline const ::ignition::msgs::Axis& Joint::_internal_axis2() const {
  const ::ignition::msgs::Axis* p = axis2_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Axis*>(
      &::ignition::msgs::_Axis_default_instance_);
}
inline const ::ignition::msgs::Axis& Joint::axis2() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.axis2)
  return _internal_axis2();
}
inline void Joint::unsafe_arena_set_allocated_axis2(
    ::ignition::msgs::Axis* axis2) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis2_);
  }
  axis2_ = axis2;
  if (axis2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.axis2)
}
inline ::ignition::msgs::Axis* Joint::release_axis2() {
  auto temp = unsafe_arena_release_axis2();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Axis* Joint::unsafe_arena_release_axis2() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.axis2)
  
  ::ignition::msgs::Axis* temp = axis2_;
  axis2_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Axis* Joint::_internal_mutable_axis2() {
  
  if (axis2_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Axis>(GetArena());
    axis2_ = p;
  }
  return axis2_;
}
inline ::ignition::msgs::Axis* Joint::mutable_axis2() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.axis2)
  return _internal_mutable_axis2();
}
inline void Joint::set_allocated_axis2(::ignition::msgs::Axis* axis2) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis2_);
  }
  if (axis2) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(axis2)->GetArena();
    if (message_arena != submessage_arena) {
      axis2 = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, axis2, submessage_arena);
    }
    
  } else {
    
  }
  axis2_ = axis2;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.axis2)
}

// double cfm = 12;
inline void Joint::clear_cfm() {
  cfm_ = 0;
}
inline double Joint::_internal_cfm() const {
  return cfm_;
}
inline double Joint::cfm() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.cfm)
  return _internal_cfm();
}
inline void Joint::_internal_set_cfm(double value) {
  
  cfm_ = value;
}
inline void Joint::set_cfm(double value) {
  _internal_set_cfm(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.cfm)
}

// double bounce = 13;
inline void Joint::clear_bounce() {
  bounce_ = 0;
}
inline double Joint::_internal_bounce() const {
  return bounce_;
}
inline double Joint::bounce() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.bounce)
  return _internal_bounce();
}
inline void Joint::_internal_set_bounce(double value) {
  
  bounce_ = value;
}
inline void Joint::set_bounce(double value) {
  _internal_set_bounce(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.bounce)
}

// double fudge_factor = 14;
inline void Joint::clear_fudge_factor() {
  fudge_factor_ = 0;
}
inline double Joint::_internal_fudge_factor() const {
  return fudge_factor_;
}
inline double Joint::fudge_factor() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.fudge_factor)
  return _internal_fudge_factor();
}
inline void Joint::_internal_set_fudge_factor(double value) {
  
  fudge_factor_ = value;
}
inline void Joint::set_fudge_factor(double value) {
  _internal_set_fudge_factor(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.fudge_factor)
}

// double limit_cfm = 15;
inline void Joint::clear_limit_cfm() {
  limit_cfm_ = 0;
}
inline double Joint::_internal_limit_cfm() const {
  return limit_cfm_;
}
inline double Joint::limit_cfm() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.limit_cfm)
  return _internal_limit_cfm();
}
inline void Joint::_internal_set_limit_cfm(double value) {
  
  limit_cfm_ = value;
}
inline void Joint::set_limit_cfm(double value) {
  _internal_set_limit_cfm(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.limit_cfm)
}

// double limit_erp = 16;
inline void Joint::clear_limit_erp() {
  limit_erp_ = 0;
}
inline double Joint::_internal_limit_erp() const {
  return limit_erp_;
}
inline double Joint::limit_erp() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.limit_erp)
  return _internal_limit_erp();
}
inline void Joint::_internal_set_limit_erp(double value) {
  
  limit_erp_ = value;
}
inline void Joint::set_limit_erp(double value) {
  _internal_set_limit_erp(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.limit_erp)
}

// double suspension_cfm = 17;
inline void Joint::clear_suspension_cfm() {
  suspension_cfm_ = 0;
}
inline double Joint::_internal_suspension_cfm() const {
  return suspension_cfm_;
}
inline double Joint::suspension_cfm() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.suspension_cfm)
  return _internal_suspension_cfm();
}
inline void Joint::_internal_set_suspension_cfm(double value) {
  
  suspension_cfm_ = value;
}
inline void Joint::set_suspension_cfm(double value) {
  _internal_set_suspension_cfm(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.suspension_cfm)
}

// double suspension_erp = 18;
inline void Joint::clear_suspension_erp() {
  suspension_erp_ = 0;
}
inline double Joint::_internal_suspension_erp() const {
  return suspension_erp_;
}
inline double Joint::suspension_erp() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.suspension_erp)
  return _internal_suspension_erp();
}
inline void Joint::_internal_set_suspension_erp(double value) {
  
  suspension_erp_ = value;
}
inline void Joint::set_suspension_erp(double value) {
  _internal_set_suspension_erp(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Joint.suspension_erp)
}

// .ignition.msgs.Joint.Gearbox gearbox = 19;
inline bool Joint::_internal_has_gearbox() const {
  return this != internal_default_instance() && gearbox_ != nullptr;
}
inline bool Joint::has_gearbox() const {
  return _internal_has_gearbox();
}
inline void Joint::clear_gearbox() {
  if (GetArena() == nullptr && gearbox_ != nullptr) {
    delete gearbox_;
  }
  gearbox_ = nullptr;
}
inline const ::ignition::msgs::Joint_Gearbox& Joint::_internal_gearbox() const {
  const ::ignition::msgs::Joint_Gearbox* p = gearbox_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Joint_Gearbox*>(
      &::ignition::msgs::_Joint_Gearbox_default_instance_);
}
inline const ::ignition::msgs::Joint_Gearbox& Joint::gearbox() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.gearbox)
  return _internal_gearbox();
}
inline void Joint::unsafe_arena_set_allocated_gearbox(
    ::ignition::msgs::Joint_Gearbox* gearbox) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(gearbox_);
  }
  gearbox_ = gearbox;
  if (gearbox) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.gearbox)
}
inline ::ignition::msgs::Joint_Gearbox* Joint::release_gearbox() {
  auto temp = unsafe_arena_release_gearbox();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Joint_Gearbox* Joint::unsafe_arena_release_gearbox() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.gearbox)
  
  ::ignition::msgs::Joint_Gearbox* temp = gearbox_;
  gearbox_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Joint_Gearbox* Joint::_internal_mutable_gearbox() {
  
  if (gearbox_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Joint_Gearbox>(GetArena());
    gearbox_ = p;
  }
  return gearbox_;
}
inline ::ignition::msgs::Joint_Gearbox* Joint::mutable_gearbox() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.gearbox)
  return _internal_mutable_gearbox();
}
inline void Joint::set_allocated_gearbox(::ignition::msgs::Joint_Gearbox* gearbox) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete gearbox_;
  }
  if (gearbox) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(gearbox);
    if (message_arena != submessage_arena) {
      gearbox = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gearbox, submessage_arena);
    }
    
  } else {
    
  }
  gearbox_ = gearbox;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.gearbox)
}

// .ignition.msgs.Joint.Screw screw = 20;
inline bool Joint::_internal_has_screw() const {
  return this != internal_default_instance() && screw_ != nullptr;
}
inline bool Joint::has_screw() const {
  return _internal_has_screw();
}
inline void Joint::clear_screw() {
  if (GetArena() == nullptr && screw_ != nullptr) {
    delete screw_;
  }
  screw_ = nullptr;
}
inline const ::ignition::msgs::Joint_Screw& Joint::_internal_screw() const {
  const ::ignition::msgs::Joint_Screw* p = screw_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Joint_Screw*>(
      &::ignition::msgs::_Joint_Screw_default_instance_);
}
inline const ::ignition::msgs::Joint_Screw& Joint::screw() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.screw)
  return _internal_screw();
}
inline void Joint::unsafe_arena_set_allocated_screw(
    ::ignition::msgs::Joint_Screw* screw) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(screw_);
  }
  screw_ = screw;
  if (screw) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Joint.screw)
}
inline ::ignition::msgs::Joint_Screw* Joint::release_screw() {
  auto temp = unsafe_arena_release_screw();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Joint_Screw* Joint::unsafe_arena_release_screw() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Joint.screw)
  
  ::ignition::msgs::Joint_Screw* temp = screw_;
  screw_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Joint_Screw* Joint::_internal_mutable_screw() {
  
  if (screw_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Joint_Screw>(GetArena());
    screw_ = p;
  }
  return screw_;
}
inline ::ignition::msgs::Joint_Screw* Joint::mutable_screw() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.screw)
  return _internal_mutable_screw();
}
inline void Joint::set_allocated_screw(::ignition::msgs::Joint_Screw* screw) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete screw_;
  }
  if (screw) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(screw);
    if (message_arena != submessage_arena) {
      screw = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, screw, submessage_arena);
    }
    
  } else {
    
  }
  screw_ = screw;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Joint.screw)
}

// repeated .ignition.msgs.Sensor sensor = 21;
inline int Joint::_internal_sensor_size() const {
  return sensor_.size();
}
inline int Joint::sensor_size() const {
  return _internal_sensor_size();
}
inline ::ignition::msgs::Sensor* Joint::mutable_sensor(int index) {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Joint.sensor)
  return sensor_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Sensor >*
Joint::mutable_sensor() {
  // @@protoc_insertion_point(field_mutable_list:ignition.msgs.Joint.sensor)
  return &sensor_;
}
inline const ::ignition::msgs::Sensor& Joint::_internal_sensor(int index) const {
  return sensor_.Get(index);
}
inline const ::ignition::msgs::Sensor& Joint::sensor(int index) const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Joint.sensor)
  return _internal_sensor(index);
}
inline ::ignition::msgs::Sensor* Joint::_internal_add_sensor() {
  return sensor_.Add();
}
inline ::ignition::msgs::Sensor* Joint::add_sensor() {
  // @@protoc_insertion_point(field_add:ignition.msgs.Joint.sensor)
  return _internal_add_sensor();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ignition::msgs::Sensor >&
Joint::sensor() const {
  // @@protoc_insertion_point(field_list:ignition.msgs.Joint.sensor)
  return sensor_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


typedef std::unique_ptr<Joint> JointUniquePtr;
typedef std::unique_ptr<const Joint> ConstJointUniquePtr;
typedef std::shared_ptr<Joint> JointSharedPtr;
typedef std::shared_ptr<const Joint> ConstJointSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ignition::msgs::Joint_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ignition::msgs::Joint_Type>() {
  return ::ignition::msgs::Joint_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fjoint_2eproto
