// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/propagation_particle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fpropagation_5fparticle_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fpropagation_5fparticle_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fpropagation_5fparticle_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fpropagation_5fparticle_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fpropagation_5fparticle_2eproto;
namespace ignition {
namespace msgs {
class PropagationParticle;
class PropagationParticleDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern PropagationParticleDefaultTypeInternal _PropagationParticle_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::PropagationParticle* Arena::CreateMaybeMessage<::ignition::msgs::PropagationParticle>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE PropagationParticle PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.PropagationParticle) */ {
 public:
  inline PropagationParticle() : PropagationParticle(nullptr) {};
  virtual ~PropagationParticle();

  PropagationParticle(const PropagationParticle& from);
  PropagationParticle(PropagationParticle&& from) noexcept
    : PropagationParticle() {
    *this = ::std::move(from);
  }

  inline PropagationParticle& operator=(const PropagationParticle& from) {
    CopyFrom(from);
    return *this;
  }
  inline PropagationParticle& operator=(PropagationParticle&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PropagationParticle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PropagationParticle* internal_default_instance() {
    return reinterpret_cast<const PropagationParticle*>(
               &_PropagationParticle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PropagationParticle& a, PropagationParticle& b) {
    a.Swap(&b);
  }
  inline void Swap(PropagationParticle* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PropagationParticle* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PropagationParticle* New() const final {
    return CreateMaybeMessage<PropagationParticle>(nullptr);
  }

  PropagationParticle* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PropagationParticle>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PropagationParticle& from);
  void MergeFrom(const PropagationParticle& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PropagationParticle* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.PropagationParticle";
  }
  protected:
  explicit PropagationParticle(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fpropagation_5fparticle_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fpropagation_5fparticle_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kSignalLevelFieldNumber = 4,
  };
  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // double x = 2;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 3;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double signal_level = 4;
  void clear_signal_level();
  double signal_level() const;
  void set_signal_level(double value);
  private:
  double _internal_signal_level() const;
  void _internal_set_signal_level(double value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.PropagationParticle)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ignition::msgs::Header* header_;
  double x_;
  double y_;
  double signal_level_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fpropagation_5fparticle_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PropagationParticle

// .ignition.msgs.Header header = 1;
inline bool PropagationParticle::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool PropagationParticle::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& PropagationParticle::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& PropagationParticle::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PropagationParticle.header)
  return _internal_header();
}
inline void PropagationParticle::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.PropagationParticle.header)
}
inline ::ignition::msgs::Header* PropagationParticle::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* PropagationParticle::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.PropagationParticle.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* PropagationParticle::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* PropagationParticle::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.PropagationParticle.header)
  return _internal_mutable_header();
}
inline void PropagationParticle::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.PropagationParticle.header)
}

// double x = 2;
inline void PropagationParticle::clear_x() {
  x_ = 0;
}
inline double PropagationParticle::_internal_x() const {
  return x_;
}
inline double PropagationParticle::x() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PropagationParticle.x)
  return _internal_x();
}
inline void PropagationParticle::_internal_set_x(double value) {
  
  x_ = value;
}
inline void PropagationParticle::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.PropagationParticle.x)
}

// double y = 3;
inline void PropagationParticle::clear_y() {
  y_ = 0;
}
inline double PropagationParticle::_internal_y() const {
  return y_;
}
inline double PropagationParticle::y() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PropagationParticle.y)
  return _internal_y();
}
inline void PropagationParticle::_internal_set_y(double value) {
  
  y_ = value;
}
inline void PropagationParticle::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.PropagationParticle.y)
}

// double signal_level = 4;
inline void PropagationParticle::clear_signal_level() {
  signal_level_ = 0;
}
inline double PropagationParticle::_internal_signal_level() const {
  return signal_level_;
}
inline double PropagationParticle::signal_level() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.PropagationParticle.signal_level)
  return _internal_signal_level();
}
inline void PropagationParticle::_internal_set_signal_level(double value) {
  
  signal_level_ = value;
}
inline void PropagationParticle::set_signal_level(double value) {
  _internal_set_signal_level(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.PropagationParticle.signal_level)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<PropagationParticle> PropagationParticleUniquePtr;
typedef std::unique_ptr<const PropagationParticle> ConstPropagationParticleUniquePtr;
typedef std::shared_ptr<PropagationParticle> PropagationParticleSharedPtr;
typedef std::shared_ptr<const PropagationParticle> ConstPropagationParticleSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fpropagation_5fparticle_2eproto
