// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/spherical_coordinates.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/entity.pb.h"
#include "ignition/msgs/header.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto;
namespace ignition {
namespace msgs {
class SphericalCoordinates;
class SphericalCoordinatesDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern SphericalCoordinatesDefaultTypeInternal _SphericalCoordinates_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::SphericalCoordinates* Arena::CreateMaybeMessage<::ignition::msgs::SphericalCoordinates>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

enum SphericalCoordinates_SurfaceModel : int {
  SphericalCoordinates_SurfaceModel_EARTH_WGS84 = 0,
  SphericalCoordinates_SurfaceModel_SphericalCoordinates_SurfaceModel_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SphericalCoordinates_SurfaceModel_SphericalCoordinates_SurfaceModel_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
IGNITION_MSGS_VISIBLE bool SphericalCoordinates_SurfaceModel_IsValid(int value);
constexpr SphericalCoordinates_SurfaceModel SphericalCoordinates_SurfaceModel_SurfaceModel_MIN = SphericalCoordinates_SurfaceModel_EARTH_WGS84;
constexpr SphericalCoordinates_SurfaceModel SphericalCoordinates_SurfaceModel_SurfaceModel_MAX = SphericalCoordinates_SurfaceModel_EARTH_WGS84;
constexpr int SphericalCoordinates_SurfaceModel_SurfaceModel_ARRAYSIZE = SphericalCoordinates_SurfaceModel_SurfaceModel_MAX + 1;

IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SphericalCoordinates_SurfaceModel_descriptor();
template<typename T>
inline const std::string& SphericalCoordinates_SurfaceModel_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SphericalCoordinates_SurfaceModel>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SphericalCoordinates_SurfaceModel_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SphericalCoordinates_SurfaceModel_descriptor(), enum_t_value);
}
inline bool SphericalCoordinates_SurfaceModel_Parse(
    const std::string& name, SphericalCoordinates_SurfaceModel* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SphericalCoordinates_SurfaceModel>(
    SphericalCoordinates_SurfaceModel_descriptor(), name, value);
}
// ===================================================================

class IGNITION_MSGS_VISIBLE SphericalCoordinates PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.SphericalCoordinates) */ {
 public:
  inline SphericalCoordinates() : SphericalCoordinates(nullptr) {};
  virtual ~SphericalCoordinates();

  SphericalCoordinates(const SphericalCoordinates& from);
  SphericalCoordinates(SphericalCoordinates&& from) noexcept
    : SphericalCoordinates() {
    *this = ::std::move(from);
  }

  inline SphericalCoordinates& operator=(const SphericalCoordinates& from) {
    CopyFrom(from);
    return *this;
  }
  inline SphericalCoordinates& operator=(SphericalCoordinates&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SphericalCoordinates& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SphericalCoordinates* internal_default_instance() {
    return reinterpret_cast<const SphericalCoordinates*>(
               &_SphericalCoordinates_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SphericalCoordinates& a, SphericalCoordinates& b) {
    a.Swap(&b);
  }
  inline void Swap(SphericalCoordinates* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SphericalCoordinates* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SphericalCoordinates* New() const final {
    return CreateMaybeMessage<SphericalCoordinates>(nullptr);
  }

  SphericalCoordinates* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SphericalCoordinates>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SphericalCoordinates& from);
  void MergeFrom(const SphericalCoordinates& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SphericalCoordinates* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.SphericalCoordinates";
  }
  protected:
  explicit SphericalCoordinates(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef SphericalCoordinates_SurfaceModel SurfaceModel;
  static constexpr SurfaceModel EARTH_WGS84 =
    SphericalCoordinates_SurfaceModel_EARTH_WGS84;
  static inline bool SurfaceModel_IsValid(int value) {
    return SphericalCoordinates_SurfaceModel_IsValid(value);
  }
  static constexpr SurfaceModel SurfaceModel_MIN =
    SphericalCoordinates_SurfaceModel_SurfaceModel_MIN;
  static constexpr SurfaceModel SurfaceModel_MAX =
    SphericalCoordinates_SurfaceModel_SurfaceModel_MAX;
  static constexpr int SurfaceModel_ARRAYSIZE =
    SphericalCoordinates_SurfaceModel_SurfaceModel_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  SurfaceModel_descriptor() {
    return SphericalCoordinates_SurfaceModel_descriptor();
  }
  template<typename T>
  static inline const std::string& SurfaceModel_Name(T enum_t_value) {
    static_assert(::std::is_same<T, SurfaceModel>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function SurfaceModel_Name.");
    return SphericalCoordinates_SurfaceModel_Name(enum_t_value);
  }
  static inline bool SurfaceModel_Parse(const std::string& name,
      SurfaceModel* value) {
    return SphericalCoordinates_SurfaceModel_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kEntityFieldNumber = 7,
    kLatitudeDegFieldNumber = 3,
    kLongitudeDegFieldNumber = 4,
    kElevationFieldNumber = 5,
    kHeadingDegFieldNumber = 6,
    kSurfaceModelFieldNumber = 2,
  };
  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // .ignition.msgs.Entity entity = 7;
  bool has_entity() const;
  private:
  bool _internal_has_entity() const;
  public:
  void clear_entity();
  const ::ignition::msgs::Entity& entity() const;
  ::ignition::msgs::Entity* release_entity();
  ::ignition::msgs::Entity* mutable_entity();
  void set_allocated_entity(::ignition::msgs::Entity* entity);
  private:
  const ::ignition::msgs::Entity& _internal_entity() const;
  ::ignition::msgs::Entity* _internal_mutable_entity();
  public:
  void unsafe_arena_set_allocated_entity(
      ::ignition::msgs::Entity* entity);
  ::ignition::msgs::Entity* unsafe_arena_release_entity();

  // double latitude_deg = 3;
  void clear_latitude_deg();
  double latitude_deg() const;
  void set_latitude_deg(double value);
  private:
  double _internal_latitude_deg() const;
  void _internal_set_latitude_deg(double value);
  public:

  // double longitude_deg = 4;
  void clear_longitude_deg();
  double longitude_deg() const;
  void set_longitude_deg(double value);
  private:
  double _internal_longitude_deg() const;
  void _internal_set_longitude_deg(double value);
  public:

  // double elevation = 5;
  void clear_elevation();
  double elevation() const;
  void set_elevation(double value);
  private:
  double _internal_elevation() const;
  void _internal_set_elevation(double value);
  public:

  // double heading_deg = 6;
  void clear_heading_deg();
  double heading_deg() const;
  void set_heading_deg(double value);
  private:
  double _internal_heading_deg() const;
  void _internal_set_heading_deg(double value);
  public:

  // .ignition.msgs.SphericalCoordinates.SurfaceModel surface_model = 2;
  void clear_surface_model();
  ::ignition::msgs::SphericalCoordinates_SurfaceModel surface_model() const;
  void set_surface_model(::ignition::msgs::SphericalCoordinates_SurfaceModel value);
  private:
  ::ignition::msgs::SphericalCoordinates_SurfaceModel _internal_surface_model() const;
  void _internal_set_surface_model(::ignition::msgs::SphericalCoordinates_SurfaceModel value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.SphericalCoordinates)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Entity* entity_;
  double latitude_deg_;
  double longitude_deg_;
  double elevation_;
  double heading_deg_;
  int surface_model_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SphericalCoordinates

// .ignition.msgs.Header header = 1;
inline bool SphericalCoordinates::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool SphericalCoordinates::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& SphericalCoordinates::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& SphericalCoordinates::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.header)
  return _internal_header();
}
inline void SphericalCoordinates::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.SphericalCoordinates.header)
}
inline ::ignition::msgs::Header* SphericalCoordinates::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* SphericalCoordinates::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.SphericalCoordinates.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* SphericalCoordinates::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* SphericalCoordinates::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.SphericalCoordinates.header)
  return _internal_mutable_header();
}
inline void SphericalCoordinates::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.SphericalCoordinates.header)
}

// .ignition.msgs.SphericalCoordinates.SurfaceModel surface_model = 2;
inline void SphericalCoordinates::clear_surface_model() {
  surface_model_ = 0;
}
inline ::ignition::msgs::SphericalCoordinates_SurfaceModel SphericalCoordinates::_internal_surface_model() const {
  return static_cast< ::ignition::msgs::SphericalCoordinates_SurfaceModel >(surface_model_);
}
inline ::ignition::msgs::SphericalCoordinates_SurfaceModel SphericalCoordinates::surface_model() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.surface_model)
  return _internal_surface_model();
}
inline void SphericalCoordinates::_internal_set_surface_model(::ignition::msgs::SphericalCoordinates_SurfaceModel value) {
  
  surface_model_ = value;
}
inline void SphericalCoordinates::set_surface_model(::ignition::msgs::SphericalCoordinates_SurfaceModel value) {
  _internal_set_surface_model(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.SphericalCoordinates.surface_model)
}

// double latitude_deg = 3;
inline void SphericalCoordinates::clear_latitude_deg() {
  latitude_deg_ = 0;
}
inline double SphericalCoordinates::_internal_latitude_deg() const {
  return latitude_deg_;
}
inline double SphericalCoordinates::latitude_deg() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.latitude_deg)
  return _internal_latitude_deg();
}
inline void SphericalCoordinates::_internal_set_latitude_deg(double value) {
  
  latitude_deg_ = value;
}
inline void SphericalCoordinates::set_latitude_deg(double value) {
  _internal_set_latitude_deg(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.SphericalCoordinates.latitude_deg)
}

// double longitude_deg = 4;
inline void SphericalCoordinates::clear_longitude_deg() {
  longitude_deg_ = 0;
}
inline double SphericalCoordinates::_internal_longitude_deg() const {
  return longitude_deg_;
}
inline double SphericalCoordinates::longitude_deg() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.longitude_deg)
  return _internal_longitude_deg();
}
inline void SphericalCoordinates::_internal_set_longitude_deg(double value) {
  
  longitude_deg_ = value;
}
inline void SphericalCoordinates::set_longitude_deg(double value) {
  _internal_set_longitude_deg(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.SphericalCoordinates.longitude_deg)
}

// double elevation = 5;
inline void SphericalCoordinates::clear_elevation() {
  elevation_ = 0;
}
inline double SphericalCoordinates::_internal_elevation() const {
  return elevation_;
}
inline double SphericalCoordinates::elevation() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.elevation)
  return _internal_elevation();
}
inline void SphericalCoordinates::_internal_set_elevation(double value) {
  
  elevation_ = value;
}
inline void SphericalCoordinates::set_elevation(double value) {
  _internal_set_elevation(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.SphericalCoordinates.elevation)
}

// double heading_deg = 6;
inline void SphericalCoordinates::clear_heading_deg() {
  heading_deg_ = 0;
}
inline double SphericalCoordinates::_internal_heading_deg() const {
  return heading_deg_;
}
inline double SphericalCoordinates::heading_deg() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.heading_deg)
  return _internal_heading_deg();
}
inline void SphericalCoordinates::_internal_set_heading_deg(double value) {
  
  heading_deg_ = value;
}
inline void SphericalCoordinates::set_heading_deg(double value) {
  _internal_set_heading_deg(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.SphericalCoordinates.heading_deg)
}

// .ignition.msgs.Entity entity = 7;
inline bool SphericalCoordinates::_internal_has_entity() const {
  return this != internal_default_instance() && entity_ != nullptr;
}
inline bool SphericalCoordinates::has_entity() const {
  return _internal_has_entity();
}
inline const ::ignition::msgs::Entity& SphericalCoordinates::_internal_entity() const {
  const ::ignition::msgs::Entity* p = entity_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Entity*>(
      &::ignition::msgs::_Entity_default_instance_);
}
inline const ::ignition::msgs::Entity& SphericalCoordinates::entity() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.SphericalCoordinates.entity)
  return _internal_entity();
}
inline void SphericalCoordinates::unsafe_arena_set_allocated_entity(
    ::ignition::msgs::Entity* entity) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(entity_);
  }
  entity_ = entity;
  if (entity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.SphericalCoordinates.entity)
}
inline ::ignition::msgs::Entity* SphericalCoordinates::release_entity() {
  auto temp = unsafe_arena_release_entity();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Entity* SphericalCoordinates::unsafe_arena_release_entity() {
  // @@protoc_insertion_point(field_release:ignition.msgs.SphericalCoordinates.entity)
  
  ::ignition::msgs::Entity* temp = entity_;
  entity_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Entity* SphericalCoordinates::_internal_mutable_entity() {
  
  if (entity_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Entity>(GetArena());
    entity_ = p;
  }
  return entity_;
}
inline ::ignition::msgs::Entity* SphericalCoordinates::mutable_entity() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.SphericalCoordinates.entity)
  return _internal_mutable_entity();
}
inline void SphericalCoordinates::set_allocated_entity(::ignition::msgs::Entity* entity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(entity_);
  }
  if (entity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(entity)->GetArena();
    if (message_arena != submessage_arena) {
      entity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, entity, submessage_arena);
    }
    
  } else {
    
  }
  entity_ = entity;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.SphericalCoordinates.entity)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<SphericalCoordinates> SphericalCoordinatesUniquePtr;
typedef std::unique_ptr<const SphericalCoordinates> ConstSphericalCoordinatesUniquePtr;
typedef std::shared_ptr<SphericalCoordinates> SphericalCoordinatesSharedPtr;
typedef std::shared_ptr<const SphericalCoordinates> ConstSphericalCoordinatesSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ignition::msgs::SphericalCoordinates_SurfaceModel> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ignition::msgs::SphericalCoordinates_SurfaceModel>() {
  return ::ignition::msgs::SphericalCoordinates_SurfaceModel_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fspherical_5fcoordinates_2eproto
