// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ignition/msgs/surface.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsurface_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsurface_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/header.pb.h"
#include "ignition/msgs/friction.pb.h"
#ifndef _MSC_VER
#pragma GCC system_header
#else
#pragma warning(push)
#pragma warning(disable: 4244 4267 4100 4244 4512 4127 4068 4275 4251)
#endif
#ifdef __linux__
#include <sys/sysmacros.h>
#endif
#include <memory>
#include <ignition/msgs/Export.hh>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ignition_2fmsgs_2fsurface_2eproto IGNITION_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct IGNITION_MSGS_VISIBLE TableStruct_ignition_2fmsgs_2fsurface_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern IGNITION_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ignition_2fmsgs_2fsurface_2eproto;
namespace ignition {
namespace msgs {
class Surface;
class SurfaceDefaultTypeInternal;
IGNITION_MSGS_VISIBLE extern SurfaceDefaultTypeInternal _Surface_default_instance_;
}  // namespace msgs
}  // namespace ignition
PROTOBUF_NAMESPACE_OPEN
template<> IGNITION_MSGS_VISIBLE ::ignition::msgs::Surface* Arena::CreateMaybeMessage<::ignition::msgs::Surface>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ignition {
namespace msgs {

// ===================================================================

class IGNITION_MSGS_VISIBLE Surface PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ignition.msgs.Surface) */ {
 public:
  inline Surface() : Surface(nullptr) {};
  virtual ~Surface();

  Surface(const Surface& from);
  Surface(Surface&& from) noexcept
    : Surface() {
    *this = ::std::move(from);
  }

  inline Surface& operator=(const Surface& from) {
    CopyFrom(from);
    return *this;
  }
  inline Surface& operator=(Surface&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Surface& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Surface* internal_default_instance() {
    return reinterpret_cast<const Surface*>(
               &_Surface_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Surface& a, Surface& b) {
    a.Swap(&b);
  }
  inline void Swap(Surface* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Surface* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Surface* New() const final {
    return CreateMaybeMessage<Surface>(nullptr);
  }

  Surface* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Surface>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Surface& from);
  void MergeFrom(const Surface& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Surface* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ignition.msgs.Surface";
  }
  protected:
  explicit Surface(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ignition_2fmsgs_2fsurface_2eproto);
    return ::descriptor_table_ignition_2fmsgs_2fsurface_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kFrictionFieldNumber = 2,
    kRestitutionCoefficientFieldNumber = 3,
    kBounceThresholdFieldNumber = 4,
    kSoftCfmFieldNumber = 5,
    kSoftErpFieldNumber = 6,
    kKpFieldNumber = 7,
    kKdFieldNumber = 8,
    kMaxVelFieldNumber = 9,
    kMinDepthFieldNumber = 10,
    kCollideWithoutContactFieldNumber = 11,
    kCollideWithoutContactBitmaskFieldNumber = 12,
    kElasticModulusFieldNumber = 14,
    kCollideBitmaskFieldNumber = 13,
  };
  // .ignition.msgs.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::ignition::msgs::Header& header() const;
  ::ignition::msgs::Header* release_header();
  ::ignition::msgs::Header* mutable_header();
  void set_allocated_header(::ignition::msgs::Header* header);
  private:
  const ::ignition::msgs::Header& _internal_header() const;
  ::ignition::msgs::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::ignition::msgs::Header* header);
  ::ignition::msgs::Header* unsafe_arena_release_header();

  // .ignition.msgs.Friction friction = 2;
  bool has_friction() const;
  private:
  bool _internal_has_friction() const;
  public:
  void clear_friction();
  const ::ignition::msgs::Friction& friction() const;
  ::ignition::msgs::Friction* release_friction();
  ::ignition::msgs::Friction* mutable_friction();
  void set_allocated_friction(::ignition::msgs::Friction* friction);
  private:
  const ::ignition::msgs::Friction& _internal_friction() const;
  ::ignition::msgs::Friction* _internal_mutable_friction();
  public:
  void unsafe_arena_set_allocated_friction(
      ::ignition::msgs::Friction* friction);
  ::ignition::msgs::Friction* unsafe_arena_release_friction();

  // double restitution_coefficient = 3;
  void clear_restitution_coefficient();
  double restitution_coefficient() const;
  void set_restitution_coefficient(double value);
  private:
  double _internal_restitution_coefficient() const;
  void _internal_set_restitution_coefficient(double value);
  public:

  // double bounce_threshold = 4;
  void clear_bounce_threshold();
  double bounce_threshold() const;
  void set_bounce_threshold(double value);
  private:
  double _internal_bounce_threshold() const;
  void _internal_set_bounce_threshold(double value);
  public:

  // double soft_cfm = 5;
  void clear_soft_cfm();
  double soft_cfm() const;
  void set_soft_cfm(double value);
  private:
  double _internal_soft_cfm() const;
  void _internal_set_soft_cfm(double value);
  public:

  // double soft_erp = 6;
  void clear_soft_erp();
  double soft_erp() const;
  void set_soft_erp(double value);
  private:
  double _internal_soft_erp() const;
  void _internal_set_soft_erp(double value);
  public:

  // double kp = 7;
  void clear_kp();
  double kp() const;
  void set_kp(double value);
  private:
  double _internal_kp() const;
  void _internal_set_kp(double value);
  public:

  // double kd = 8;
  void clear_kd();
  double kd() const;
  void set_kd(double value);
  private:
  double _internal_kd() const;
  void _internal_set_kd(double value);
  public:

  // double max_vel = 9;
  void clear_max_vel();
  double max_vel() const;
  void set_max_vel(double value);
  private:
  double _internal_max_vel() const;
  void _internal_set_max_vel(double value);
  public:

  // double min_depth = 10;
  void clear_min_depth();
  double min_depth() const;
  void set_min_depth(double value);
  private:
  double _internal_min_depth() const;
  void _internal_set_min_depth(double value);
  public:

  // bool collide_without_contact = 11;
  void clear_collide_without_contact();
  bool collide_without_contact() const;
  void set_collide_without_contact(bool value);
  private:
  bool _internal_collide_without_contact() const;
  void _internal_set_collide_without_contact(bool value);
  public:

  // uint32 collide_without_contact_bitmask = 12;
  void clear_collide_without_contact_bitmask();
  ::PROTOBUF_NAMESPACE_ID::uint32 collide_without_contact_bitmask() const;
  void set_collide_without_contact_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_collide_without_contact_bitmask() const;
  void _internal_set_collide_without_contact_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // double elastic_modulus = 14;
  void clear_elastic_modulus();
  double elastic_modulus() const;
  void set_elastic_modulus(double value);
  private:
  double _internal_elastic_modulus() const;
  void _internal_set_elastic_modulus(double value);
  public:

  // uint32 collide_bitmask = 13;
  void clear_collide_bitmask();
  ::PROTOBUF_NAMESPACE_ID::uint32 collide_bitmask() const;
  void set_collide_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_collide_bitmask() const;
  void _internal_set_collide_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ignition.msgs.Surface)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ignition::msgs::Header* header_;
  ::ignition::msgs::Friction* friction_;
  double restitution_coefficient_;
  double bounce_threshold_;
  double soft_cfm_;
  double soft_erp_;
  double kp_;
  double kd_;
  double max_vel_;
  double min_depth_;
  bool collide_without_contact_;
  ::PROTOBUF_NAMESPACE_ID::uint32 collide_without_contact_bitmask_;
  double elastic_modulus_;
  ::PROTOBUF_NAMESPACE_ID::uint32 collide_bitmask_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ignition_2fmsgs_2fsurface_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Surface

// .ignition.msgs.Header header = 1;
inline bool Surface::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Surface::has_header() const {
  return _internal_has_header();
}
inline const ::ignition::msgs::Header& Surface::_internal_header() const {
  const ::ignition::msgs::Header* p = header_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Header*>(
      &::ignition::msgs::_Header_default_instance_);
}
inline const ::ignition::msgs::Header& Surface::header() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.header)
  return _internal_header();
}
inline void Surface::unsafe_arena_set_allocated_header(
    ::ignition::msgs::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Surface.header)
}
inline ::ignition::msgs::Header* Surface::release_header() {
  auto temp = unsafe_arena_release_header();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Header* Surface::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Surface.header)
  
  ::ignition::msgs::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Header* Surface::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::ignition::msgs::Header* Surface::mutable_header() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Surface.header)
  return _internal_mutable_header();
}
inline void Surface::set_allocated_header(::ignition::msgs::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Surface.header)
}

// .ignition.msgs.Friction friction = 2;
inline bool Surface::_internal_has_friction() const {
  return this != internal_default_instance() && friction_ != nullptr;
}
inline bool Surface::has_friction() const {
  return _internal_has_friction();
}
inline const ::ignition::msgs::Friction& Surface::_internal_friction() const {
  const ::ignition::msgs::Friction* p = friction_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ignition::msgs::Friction*>(
      &::ignition::msgs::_Friction_default_instance_);
}
inline const ::ignition::msgs::Friction& Surface::friction() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.friction)
  return _internal_friction();
}
inline void Surface::unsafe_arena_set_allocated_friction(
    ::ignition::msgs::Friction* friction) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(friction_);
  }
  friction_ = friction;
  if (friction) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ignition.msgs.Surface.friction)
}
inline ::ignition::msgs::Friction* Surface::release_friction() {
  auto temp = unsafe_arena_release_friction();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ignition::msgs::Friction* Surface::unsafe_arena_release_friction() {
  // @@protoc_insertion_point(field_release:ignition.msgs.Surface.friction)
  
  ::ignition::msgs::Friction* temp = friction_;
  friction_ = nullptr;
  return temp;
}
inline ::ignition::msgs::Friction* Surface::_internal_mutable_friction() {
  
  if (friction_ == nullptr) {
    auto* p = CreateMaybeMessage<::ignition::msgs::Friction>(GetArena());
    friction_ = p;
  }
  return friction_;
}
inline ::ignition::msgs::Friction* Surface::mutable_friction() {
  // @@protoc_insertion_point(field_mutable:ignition.msgs.Surface.friction)
  return _internal_mutable_friction();
}
inline void Surface::set_allocated_friction(::ignition::msgs::Friction* friction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(friction_);
  }
  if (friction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(friction)->GetArena();
    if (message_arena != submessage_arena) {
      friction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, friction, submessage_arena);
    }
    
  } else {
    
  }
  friction_ = friction;
  // @@protoc_insertion_point(field_set_allocated:ignition.msgs.Surface.friction)
}

// double restitution_coefficient = 3;
inline void Surface::clear_restitution_coefficient() {
  restitution_coefficient_ = 0;
}
inline double Surface::_internal_restitution_coefficient() const {
  return restitution_coefficient_;
}
inline double Surface::restitution_coefficient() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.restitution_coefficient)
  return _internal_restitution_coefficient();
}
inline void Surface::_internal_set_restitution_coefficient(double value) {
  
  restitution_coefficient_ = value;
}
inline void Surface::set_restitution_coefficient(double value) {
  _internal_set_restitution_coefficient(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.restitution_coefficient)
}

// double bounce_threshold = 4;
inline void Surface::clear_bounce_threshold() {
  bounce_threshold_ = 0;
}
inline double Surface::_internal_bounce_threshold() const {
  return bounce_threshold_;
}
inline double Surface::bounce_threshold() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.bounce_threshold)
  return _internal_bounce_threshold();
}
inline void Surface::_internal_set_bounce_threshold(double value) {
  
  bounce_threshold_ = value;
}
inline void Surface::set_bounce_threshold(double value) {
  _internal_set_bounce_threshold(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.bounce_threshold)
}

// double soft_cfm = 5;
inline void Surface::clear_soft_cfm() {
  soft_cfm_ = 0;
}
inline double Surface::_internal_soft_cfm() const {
  return soft_cfm_;
}
inline double Surface::soft_cfm() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.soft_cfm)
  return _internal_soft_cfm();
}
inline void Surface::_internal_set_soft_cfm(double value) {
  
  soft_cfm_ = value;
}
inline void Surface::set_soft_cfm(double value) {
  _internal_set_soft_cfm(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.soft_cfm)
}

// double soft_erp = 6;
inline void Surface::clear_soft_erp() {
  soft_erp_ = 0;
}
inline double Surface::_internal_soft_erp() const {
  return soft_erp_;
}
inline double Surface::soft_erp() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.soft_erp)
  return _internal_soft_erp();
}
inline void Surface::_internal_set_soft_erp(double value) {
  
  soft_erp_ = value;
}
inline void Surface::set_soft_erp(double value) {
  _internal_set_soft_erp(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.soft_erp)
}

// double kp = 7;
inline void Surface::clear_kp() {
  kp_ = 0;
}
inline double Surface::_internal_kp() const {
  return kp_;
}
inline double Surface::kp() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.kp)
  return _internal_kp();
}
inline void Surface::_internal_set_kp(double value) {
  
  kp_ = value;
}
inline void Surface::set_kp(double value) {
  _internal_set_kp(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.kp)
}

// double kd = 8;
inline void Surface::clear_kd() {
  kd_ = 0;
}
inline double Surface::_internal_kd() const {
  return kd_;
}
inline double Surface::kd() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.kd)
  return _internal_kd();
}
inline void Surface::_internal_set_kd(double value) {
  
  kd_ = value;
}
inline void Surface::set_kd(double value) {
  _internal_set_kd(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.kd)
}

// double max_vel = 9;
inline void Surface::clear_max_vel() {
  max_vel_ = 0;
}
inline double Surface::_internal_max_vel() const {
  return max_vel_;
}
inline double Surface::max_vel() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.max_vel)
  return _internal_max_vel();
}
inline void Surface::_internal_set_max_vel(double value) {
  
  max_vel_ = value;
}
inline void Surface::set_max_vel(double value) {
  _internal_set_max_vel(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.max_vel)
}

// double min_depth = 10;
inline void Surface::clear_min_depth() {
  min_depth_ = 0;
}
inline double Surface::_internal_min_depth() const {
  return min_depth_;
}
inline double Surface::min_depth() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.min_depth)
  return _internal_min_depth();
}
inline void Surface::_internal_set_min_depth(double value) {
  
  min_depth_ = value;
}
inline void Surface::set_min_depth(double value) {
  _internal_set_min_depth(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.min_depth)
}

// bool collide_without_contact = 11;
inline void Surface::clear_collide_without_contact() {
  collide_without_contact_ = false;
}
inline bool Surface::_internal_collide_without_contact() const {
  return collide_without_contact_;
}
inline bool Surface::collide_without_contact() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.collide_without_contact)
  return _internal_collide_without_contact();
}
inline void Surface::_internal_set_collide_without_contact(bool value) {
  
  collide_without_contact_ = value;
}
inline void Surface::set_collide_without_contact(bool value) {
  _internal_set_collide_without_contact(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.collide_without_contact)
}

// uint32 collide_without_contact_bitmask = 12;
inline void Surface::clear_collide_without_contact_bitmask() {
  collide_without_contact_bitmask_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Surface::_internal_collide_without_contact_bitmask() const {
  return collide_without_contact_bitmask_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Surface::collide_without_contact_bitmask() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.collide_without_contact_bitmask)
  return _internal_collide_without_contact_bitmask();
}
inline void Surface::_internal_set_collide_without_contact_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  collide_without_contact_bitmask_ = value;
}
inline void Surface::set_collide_without_contact_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_collide_without_contact_bitmask(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.collide_without_contact_bitmask)
}

// uint32 collide_bitmask = 13;
inline void Surface::clear_collide_bitmask() {
  collide_bitmask_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Surface::_internal_collide_bitmask() const {
  return collide_bitmask_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Surface::collide_bitmask() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.collide_bitmask)
  return _internal_collide_bitmask();
}
inline void Surface::_internal_set_collide_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  collide_bitmask_ = value;
}
inline void Surface::set_collide_bitmask(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_collide_bitmask(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.collide_bitmask)
}

// double elastic_modulus = 14;
inline void Surface::clear_elastic_modulus() {
  elastic_modulus_ = 0;
}
inline double Surface::_internal_elastic_modulus() const {
  return elastic_modulus_;
}
inline double Surface::elastic_modulus() const {
  // @@protoc_insertion_point(field_get:ignition.msgs.Surface.elastic_modulus)
  return _internal_elastic_modulus();
}
inline void Surface::_internal_set_elastic_modulus(double value) {
  
  elastic_modulus_ = value;
}
inline void Surface::set_elastic_modulus(double value) {
  _internal_set_elastic_modulus(value);
  // @@protoc_insertion_point(field_set:ignition.msgs.Surface.elastic_modulus)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef std::unique_ptr<Surface> SurfaceUniquePtr;
typedef std::unique_ptr<const Surface> ConstSurfaceUniquePtr;
typedef std::shared_ptr<Surface> SurfaceSharedPtr;
typedef std::shared_ptr<const Surface> ConstSurfaceSharedPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace ignition

#ifdef _MSC_VER
#pragma warning(pop)
#endif
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ignition_2fmsgs_2fsurface_2eproto
