# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/air_pressure_sensor.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
require 'ignition/msgs/sensor_noise_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/air_pressure_sensor.proto", :syntax => :proto3) do
    add_message "ignition.msgs.AirPressureSensor" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :reference_altitude, :double, 2
      optional :pressure_noise, :message, 3, "ignition.msgs.SensorNoise"
    end
  end
end

module Ignition
  module Msgs
    AirPressureSensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.AirPressureSensor").msgclass
  end
end
