# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/boxgeom.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
require 'ignition/msgs/vector3d_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/boxgeom.proto", :syntax => :proto3) do
    add_message "ignition.msgs.BoxGeom" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :size, :message, 2, "ignition.msgs.Vector3d"
    end
  end
end

module Ignition
  module Msgs
    BoxGeom = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.BoxGeom").msgclass
  end
end
