# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/dataframe.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/dataframe.proto", :syntax => :proto3) do
    add_message "ignition.msgs.Dataframe" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :src_address, :string, 2
      optional :dst_address, :string, 3
      optional :data, :bytes, 4
    end
  end
end

module Ignition
  module Msgs
    Dataframe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.Dataframe").msgclass
  end
end
