# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/magnetometer_sensor.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
require 'ignition/msgs/sensor_noise_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/magnetometer_sensor.proto", :syntax => :proto3) do
    add_message "ignition.msgs.MagnetometerSensor" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :x_noise, :message, 2, "ignition.msgs.SensorNoise"
      optional :y_noise, :message, 3, "ignition.msgs.SensorNoise"
      optional :z_noise, :message, 4, "ignition.msgs.SensorNoise"
    end
  end
end

module Ignition
  module Msgs
    MagnetometerSensor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.MagnetometerSensor").msgclass
  end
end
