# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/plugin.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/plugin.proto", :syntax => :proto3) do
    add_message "ignition.msgs.Plugin" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :name, :string, 2
      optional :filename, :string, 3
      optional :innerxml, :string, 4
    end
  end
end

module Ignition
  module Msgs
    Plugin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.Plugin").msgclass
  end
end
