# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/pose_v.proto

require 'google/protobuf'

require 'ignition/msgs/pose_pb'
require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/pose_v.proto", :syntax => :proto3) do
    add_message "ignition.msgs.Pose_V" do
      optional :header, :message, 1, "ignition.msgs.Header"
      repeated :pose, :message, 2, "ignition.msgs.Pose"
    end
  end
end

module Ignition
  module Msgs
    Pose_V = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.Pose_V").msgclass
  end
end
