# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/publishers.proto

require 'google/protobuf'

require 'ignition/msgs/publish_pb'
require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/publishers.proto", :syntax => :proto3) do
    add_message "ignition.msgs.Publishers" do
      optional :header, :message, 1, "ignition.msgs.Header"
      repeated :publisher, :message, 2, "ignition.msgs.Publish"
    end
  end
end

module Ignition
  module Msgs
    Publishers = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.Publishers").msgclass
  end
end
