# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/response.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/response.proto", :syntax => :proto3) do
    add_message "ignition.msgs.Response" do
      optional :header, :message, 1, "ignition.msgs.Header"
      optional :id, :int32, 2
      optional :request, :string, 3
      optional :response, :string, 4
      optional :type, :string, 5
      optional :serialized_data, :bytes, 6
    end
  end
end

module Ignition
  module Msgs
    Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.Response").msgclass
  end
end
