# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/uint64_v.proto

require 'google/protobuf'

require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/uint64_v.proto", :syntax => :proto3) do
    add_message "ignition.msgs.UInt64_V" do
      optional :header, :message, 1, "ignition.msgs.Header"
      repeated :data, :uint64, 2
    end
  end
end

module Ignition
  module Msgs
    UInt64_V = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.UInt64_V").msgclass
  end
end
