# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ignition/msgs/wireless_nodes.proto

require 'google/protobuf'

require 'ignition/msgs/wireless_node_pb'
require 'ignition/msgs/header_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ignition/msgs/wireless_nodes.proto", :syntax => :proto3) do
    add_message "ignition.msgs.WirelessNodes" do
      optional :header, :message, 1, "ignition.msgs.Header"
      repeated :node, :message, 2, "ignition.msgs.WirelessNode"
    end
  end
end

module Ignition
  module Msgs
    WirelessNodes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ignition.msgs.WirelessNodes").msgclass
  end
end
