<?xml version="1.0"?>
<package format="3">
  <name>gimbal_position</name>
  <version>0.0.0</version>
  <description>Package for publishing joint state messages</description>

  <maintainer email="your.email@example.com">Your Name</maintainer>
  <license>Apache License 2.0</license> <!-- 修正许可证名称 -->

  <!-- 添加构建工具依赖 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- 调整依赖顺序 -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs </depend> 
  <depend>tf2_geometry_msgs</depend>
  <depend>launch_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
