<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>chassis_odom</name>
  <version>0.0.0</version>
  <description>Calculate angle deviation between robot and global path</description>

  <!-- 维护者信息（需修改为实际信息） -->
  <maintainer email="your.email@example.com">Your Name</maintainer>
  <license>Apache License 2.0</license>

  <!-- 构建工具依赖 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS2 功能包依赖 -->
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>launch_ros</depend>
  <depend>rclcpp_action</depend>
  <depend>nav2_msgs</depend>
  <depend>customize_messages</depend>
  <!-- 编译和运行环境配置 -->
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
